In [1]:
import numpy as np

In [2]:
# 넘파이로 텐서를 만드는 방법

In [3]:
# 1차원 텐서
# 리스트 먼저 만들기
# 넘파이의 어레이를 이용
t = np.array([1,2,3,4])
t

array([1, 2, 3, 4])

In [4]:
t.ndim # 텐서의 크기(4,)는 (1,4)를 의미함

1

In [5]:
# 실수 형태로 만들어 보기
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
t

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [6]:
t.ndim

2

In [7]:
t.shape

(4, 3)

In [8]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [9]:
# t.shape, t.size()에서 괄호가 있고 없고 차이는 객체지향 프로그래밍을 알아야하는데
# t.shape = 속성, t.size() = 함수(메서드)
# 내차.달린다()   자동차(클래스)
# 자동차 클래스로부터 파생(생성)된 실체(객체)기 내차
# t는 실체, 위에서 t=torch.FloatTensor FloatTensor에서 만들어진것
# 일반적으로 대문자로 시작하면 클래스, 클래스는 대문자로 시작함
# FloatTensor(클래스) : 대문자로 시작
# t.size()는 size라는 메서드를 클래스가 가지고 있는 것
# 클래스에서 뒤에 ()를 붙이면 객체가 만들어지고 그 객체를 t라는 변수에 담은 것
# t는 내 차와 같아짐

In [10]:
# 클래스는 설계도면 즉 붕어빵이라면 붕어빵 기계, 벽돌 공장
# 객체 : 클래스로부터 생성되는 실체
# 1. 설계도면 ->  실제건물
# 2. 붕어빵기계 -> 붕어빵
# 2. 벽돌공장 -> 벽돌
# 메서드 : 객체가 수행하는 동작(기능)
# 속성( 어트리뷰트) : 객체의 특성

# 객체지향적 프로그래밍 : 과거에는 지향하지 않았지만 객체를 지향하는 방법으로 프로그래밍
    # ex) 절차지향적 사례(과거 30년 전까지 )
        # - 붕어빵기계로 붕어빵을 판매하던 시대가 지나가고 잉어빵 시대가 도래
        # -> 붕어빵기계는 못쓰게 됨 -> 잉어빵 기계 새롭게 제작
        # 시대가 바뀔때 마다 새로 바꿔줘야함
        
    # ex) 객체지향적 사례(현재 ~ 미래)
        # - 붕어빵기계로 붕어빵을 판매하던 시대가 지나가고 잉어빵 시대가 도래, 붕어빵기계를 재사용
        # -> 붕어빵기계 재사용(붕어빵기계의 메서드, 속성 중에서 그대로 사용할 것은 사용하고, 변경할 것은
        # 변경, 버릴것은 버리고)

In [11]:
"""
class FloatTensor:
    속성 (특성)
    shape=len([0., 1., 2., 3., 4., 5., 6.])
    함수(동작)
    size(0):
    return len([0., 1., 2., 3., 4., 5., 6.])
"""

'\nclass FloatTensor:\n    속성 (특성)\n    shape=len([0., 1., 2., 3., 4., 5., 6.])\n    함수(동작)\n    size(0):\n    return len([0., 1., 2., 3., 4., 5., 6.])\n'

In [12]:
import torch

In [13]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])

In [14]:
# 행렬 연산(덧셈,뺄셈) : 두 행렬의 크기가 같아야 함
# 행렬 연산(곱셈) : 두 행렬의 마지막 차원과 첫번째 차원이 일치

In [15]:
t1 = torch.FloatTensor([[1,1]])
t2 = torch.FloatTensor([[2,2]])

In [16]:
t1.shape
t1+t2

tensor([[3., 3.]])

In [17]:
t3 = torch.FloatTensor([[1,1]]) # (1,2)
t4 = torch.FloatTensor([3])     # 자동 변경 (브로드캐스팅) : (1,) -> (1,2)
t3+t4

tensor([[4., 4.]])

In [18]:
# 2*1 + 1*2
t5 = torch.FloatTensor([[1,3]]) # [[1,3],
                                # [1,3]]
t6 = torch.FloatTensor([[1],[3]])
# [[1],   ->   [[1],[1],
# [3]]          [3],[3]]

In [19]:
t5.shape

torch.Size([1, 2])

In [20]:
t6.shape

torch.Size([2, 1])

In [21]:
t5 + t6

tensor([[2., 4.],
        [4., 6.]])

In [22]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

In [23]:
m1.matmul(m2)

tensor([[ 5.],
        [11.]])

In [24]:
t = torch.FloatTensor([[1,2],[3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [25]:
t.mean()

tensor(2.5000)

In [26]:
t.mean(dim = 0) # dim = 0은 첫번째 차원, 행렬에서는 행

tensor([2., 3.])

In [27]:
t.mean(dim = 1) # dim = 1은 두번째 차원, 행렬에서는 열, 열을 제거 -> 행만 남음

tensor([1.5000, 3.5000])

In [28]:
t.sum(dim = 0)

tensor([4., 6.])

In [29]:
t.sum(dim = -1) # 마지막 차원 제거(열 제거)

tensor([3., 7.])

In [30]:
t.max()

tensor(4.)

In [31]:
t.max(dim = 0) # 행 제거, indices(argmax) : 최대값의 인덱스

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [32]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [33]:
ft.shape

torch.Size([2, 2, 3])

In [34]:
ft.view([-1,3]) # view : 텐서 크기 변경. (-1,3)은 (?,3)표기 가능
# [2,2,3] 3차원 텐서를 2차원 텐서로 변경 (-1,3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [35]:
ft.view([4,3])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [36]:
ft.view([4,-1])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [37]:
ft= torch.FloatTensor([[0],[1],[2]])
ft

tensor([[0.],
        [1.],
        [2.]])

In [38]:
ft.squeeze()

tensor([0., 1., 2.])

In [39]:
ft2 = torch.FloatTensor([[0,1],[1,2],[2,3]])
ft2

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [40]:
ft2.squeeze() # 행크기 3, 열크기 2 -> 크기가 1인 차원이 없으므로 제거 작업 X

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [41]:
# unsqueeze : 크기가 1인 차원을 특정 위치에 추가

In [42]:
ft =torch.Tensor([0,1,2])
ft

tensor([0., 1., 2.])

In [43]:
ft.unsqueeze(0) # (1,3)

tensor([[0., 1., 2.]])

In [44]:
ft.unsqueeze(1) # (3,1)

tensor([[0.],
        [1.],
        [2.]])

In [45]:
lt = torch.LongTensor([1.0, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [46]:
lt.float()

tensor([1., 2., 3., 4.])

In [47]:
bt = torch.ByteTensor([True,False,True,False])
print(bt)

tensor([1, 0, 1, 0], dtype=torch.uint8)


In [48]:
bt.long()

tensor([1, 0, 1, 0])

In [49]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [50]:
torch.cat([x,y])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [51]:
torch.cat([x,y], dim = 0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [52]:
torch.cat([x,y], dim = 1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [53]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [54]:
torch.stack([x,y,z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [55]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [56]:
# 텐서의 크기는 그대로 두되, 새롭게 0 또는 1로 값을 채우는 것
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [57]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [58]:
x*2

tensor([[2., 4.],
        [6., 8.]])

In [59]:
x.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [60]:
x.mul_(2) # 덮어쓰기

tensor([[2., 4.],
        [6., 8.]])

In [61]:
result = 0

In [62]:
def add(num):
    result = 1 # 함수 내에서만 사용되는 변수
    result += num
    return result

In [63]:
add(3)

4

In [64]:
result1 = 0
result2 = 0

In [65]:
def add1(num):
    global result1
    result1 += num
    return result1

In [66]:
def add2(num):
    global result2
    result2 += num
    return result2

In [67]:
print(add1(3))
print(add1(4))

3
7


In [68]:
print(add2(2))
print(add2(6))

2
8


In [69]:
class Calculator:
    def __init__(self): # 클래스 -> 객체 생성될때 자동 호출 (생성자)
        self.result = 0
        print('생성자 호출됨')
    def add(self,num):
        self.result += num
        print('add함수 호출됨')
        return self.result

In [70]:
cal1 = Calculator() # 클래스 -> 객체 생성
cal2 = Calculator()

생성자 호출됨
생성자 호출됨


In [71]:
cal1.add(3)

add함수 호출됨


3

In [72]:
cal1.add(4)

add함수 호출됨


7

In [73]:
cal2.add(2)

add함수 호출됨


2

In [74]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [75]:
torch.manual_seed(1)

In [76]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [77]:
x_train.shape

torch.Size([3, 1])

In [78]:
W = torch.zeros(1,requires_grad = True) # requires_grad = True  W는 변수
W

tensor([0.], requires_grad=True)

In [79]:
b = torch.zeros(1,requires_grad = True)

In [80]:
# 초기 모델 가설 함수 : y = 0*x +0
# hx = W * x_train + b

In [81]:
# hx

In [82]:
# cost
# cost = torch.mean((hx - y_train)**2)
# cost

In [83]:
# optimizer = optim.SGD([W,b],lr=0.01)

In [84]:
# optimizer.zero_grad() # 미분을 해서 구한 기울기를 0으로 초기화해줌
# cost.backward() # W, b에 대한 기울기가 계산
# optimizer.step() # W,b에 대한 업데이트

In [85]:
# W # W : 2

In [86]:
# b # b : 0

In [87]:
# W.item()
# b.item()

In [88]:
optimizer = optim.SGD([W,b],lr=0.01)
for epoch in range(2000):
    hx = W * x_train + b
    cost = torch.mean((hx - y_train)**2)
    optimizer.zero_grad() 
    cost.backward() 
    optimizer.step()
    if epoch % 100 ==0 :
        print(epoch,W.item(),b.item(),cost.item())

0 0.18666668236255646 0.07999999821186066 18.66666603088379
100 1.7456912994384766 0.5780722498893738 0.04817060008645058
200 1.80009925365448 0.4544214904308319 0.029766537249088287
300 1.8428597450256348 0.35721680521965027 0.018393920734524727
400 1.876473307609558 0.28080499172210693 0.011366334743797779
500 1.9028971195220947 0.22073803842067719 0.007023668382316828
600 1.9236682653427124 0.1735200434923172 0.00434019835665822
700 1.9399964809417725 0.13640251755714417 0.0026819754857569933
800 1.952831506729126 0.10722480714321136 0.0016572937602177262
900 1.9629212617874146 0.0842885971069336 0.0010241125710308552
1000 1.9708527326583862 0.06625857204198837 0.0006328357267193496
1100 1.977087378501892 0.05208539217710495 0.0003910581872332841
1200 1.9819889068603516 0.04094360023736954 0.0002416476490907371
1300 1.9858416318893433 0.032185304909944534 0.00014932315389160067
1400 1.9888702630996704 0.025300635024905205 9.227206464856863e-05
1500 1.991250991821289 0.01988868787884

In [89]:
W.item()*5 + b.item()

9.992821462452412

In [90]:
w = torch.tensor(2.0, requires_grad = True)

In [91]:
y = w **2

In [92]:
y

tensor(4., grad_fn=<PowBackward0>)

In [93]:
z = 2*y + 5
z

tensor(13., grad_fn=<AddBackward0>)

In [94]:
z.backward()

In [95]:
w.grad # z수식을 w로 미분한 값

tensor(8.)

In [96]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [97]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [98]:
optimizer = optim.SGD([w1,w2,w3,b],lr=0.0000001) # 0.01 <= lr <= 0.001
# 1*10의 -5 승 = 1 * 0.00001
for epoch in range(2000):
    hx = w1 * x1_train + w2 * x2_train + w3 * x3_train + b
    cost = torch.mean((hx - y_train)**2)
    optimizer.zero_grad() 
    cost.backward() 
    optimizer.step()
    if epoch % 100 ==0 :
        print(epoch,w1.item(),w2.item(),w3.item(),b.item(),cost.item())
# nan : 발산의 의미

0 0.0029401201754808426 0.0029360000044107437 0.0029738000594079494 3.420000211917795e-05 29661.80078125
100 0.24016305804252625 0.2398034930229187 0.24290433526039124 0.002793786348775029 12276.9267578125
200 0.39279428124427795 0.3921634256839752 0.397259384393692 0.0045696343295276165 5081.94140625
300 0.49100565910339355 0.4901577830314636 0.49656152725219727 0.005712618585675955 2104.19189453125
400 0.5542075037956238 0.5531775951385498 0.5604471564292908 0.006448470056056976 871.80517578125
500 0.5948866009712219 0.5936970710754395 0.6015483140945435 0.006922401022166014 361.76568603515625
600 0.6210764050483704 0.6197422742843628 0.6279918551445007 0.0072278352454304695 150.67652893066406
700 0.6379450559616089 0.6364750862121582 0.6450056433677673 0.007424870505928993 63.31452560424805
800 0.6488174200057983 0.6472178101539612 0.6559532284736633 0.007552170194685459 27.156991958618164
900 0.655832052230835 0.6541066765785217 0.662997841835022 0.007634604815393686 12.19252586364

In [99]:
# 표준화 버전
x1_train = torch.FloatTensor([[0.73], [0.93], [0.89], [0.96], [0.73]])
x2_train = torch.FloatTensor([[0.80], [0.88], [0.91], [0.98], [0.66]])
x3_train = torch.FloatTensor([[0.75], [0.93], [0.90], [1.00], [0.70]])
y_train = torch.FloatTensor([[1.52], [1.85], [1.80], [1.96], [1.42]])

In [100]:
w1.item()*90 + w2.item()*90 + w3.item()*90 + b.item()
# 예상 점수 : 180.9457216821611

180.9457216821611

In [101]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [102]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [103]:
#w1 = torch.zeros(1, requires_grad=True)
#w2 = torch.zeros(1, requires_grad=True)
#w3 = torch.zeros(1, requires_grad=True)
W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [104]:
optimizer=optim.SGD([W,b],lr=0.00001)

In [106]:
for epoch in range(2000):
    hx=x_train.matmul(W) + b
    cost=torch.mean((hx - y_train)**2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch%100 ==0: 
        print(epoch ,cost.item())

0 9537.6943359375
100 5.752121448516846
200 5.510031700134277
300 5.2793989181518555
400 5.059759616851807
500 4.850369930267334
600 4.650723457336426
700 4.460408687591553
800 4.278825759887695
900 4.105560779571533
1000 3.940225124359131
1100 3.782344102859497
1200 3.6315715312957764
1300 3.4875869750976562
1400 3.3499629497528076
1500 3.218451738357544
1600 3.092745304107666
1700 2.9725329875946045
1800 2.8575236797332764
1900 2.7475745677948


In [107]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [108]:
torch.manual_seed(1)

In [109]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [110]:
model = nn.Linear(1,1)
list(model.parameters())
# 초기 모델 : y = 0.5153 * x_train -0.4414

[Parameter containing:
 tensor([[0.5153]], requires_grad=True),
 Parameter containing:
 tensor([-0.4414], requires_grad=True)]

In [111]:
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)

In [112]:
for epoch in range(2000):
    
    hx = model(x_train) # hx = x_train.matmul(W) + b
    cost = F.mse_loss(hx, y_train) # cost=torch.mean((hx - y_train)**2)
    
    optimizer.zero_grad() # 나머지는 그대로
    cost.backward()
    optimizer.step()
    if epoch%100 ==0: 
        print(epoch ,cost.item())

0 13.103541374206543
100 0.00279058120213449
200 0.00172441138420254
300 0.0010655784280970693
400 0.0006584661896340549
500 0.0004068926500622183
600 0.0002514346851967275
700 0.00015537298168055713
800 9.601024794392288e-05
900 5.9327696362743154e-05
1000 3.66610438504722e-05
1100 2.2655576685792767e-05
1200 1.3999051589053124e-05
1300 8.65114816406276e-06
1400 5.346103989722906e-06
1500 3.3032331430149497e-06
1600 2.04174443751981e-06
1700 1.2618406799447257e-06
1800 7.801028800713539e-07
1900 4.823282324650791e-07


In [113]:
list(model.parameters())

[Parameter containing:
 tensor([[1.9994]], requires_grad=True),
 Parameter containing:
 tensor([0.0014], requires_grad=True)]

In [123]:
new_var =  torch.FloatTensor([[4.0]])

In [124]:
model(new_var)

tensor([[7.9989]], grad_fn=<AddmmBackward0>)

In [125]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [126]:
model = nn.Linear(3,1) # 입력차원, 출력차원

In [127]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True),
 Parameter containing:
 tensor([0.3462], requires_grad=True)]

In [128]:
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [129]:
for epoch in range(2000):
    
    hx = model(x_train) # hx = x_train.matmul(W) + b
    cost = F.mse_loss(hx, y_train) # cost=torch.mean((hx - y_train)**2)
    
    optimizer.zero_grad() # 나머지는 그대로
    cost.backward()
    optimizer.step()
    if epoch%100 ==0: 
        print(epoch ,cost.item())

0 42134.70703125
100 5.960053443908691
200 5.654706954956055
300 5.365412712097168
400 5.091428756713867
500 4.831833839416504
600 4.585997104644775
700 4.353074550628662
800 4.132411003112793
900 3.9234554767608643
1000 3.7255024909973145
1100 3.5379719734191895
1200 3.360325574874878
1300 3.19205641746521
1400 3.0326738357543945
1500 2.881699562072754
1600 2.7386722564697266
1700 2.603201150894165
1800 2.4748456478118896
1900 2.353286027908325


In [131]:
new_var = torch.FloatTensor([90,90,90])
model(new_var)

tensor([181.3557], grad_fn=<ViewBackward0>)

In [132]:
list(model.parameters())

[Parameter containing:
 tensor([[0.8540, 0.8475, 0.3096]], requires_grad=True),
 Parameter containing:
 tensor([0.3568], requires_grad=True)]