<a href="https://colab.research.google.com/github/yknlwca/Deep_Learning/blob/master/BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 43.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.1/311.1 kB 26.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 70.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 61.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 28.8 MB/s eta 0:00:00


In [2]:
import pandas as pd
from transformers import BertTokenizer

In [3]:
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

In [4]:
result = tokenizer.tokenize('Here is the sentence I want embeddings for.')
print(result)

['here', 'is', 'the', 'sentence', 'i', 'want', 'em', '##bed', '##ding', '##s', 'for', '.']


In [5]:
print(tokenizer.vocab['here'])

2182


In [6]:
from transformers import TFBertForMaskedLM

In [7]:
model = TFBertForMaskedLM.from_pretrained('bert-large-uncased')
# BERT를 마스크드 언어 모델 구조로 읽기

All PyTorch model weights were used when initializing TFBertForMaskedLM.

All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


In [8]:
from transformers import AutoTokenizer

In [9]:
tokenizer = AutoTokenizer.from_pretrained('bert-large-uncased')
# bert-large-uncased 모델이 학습될 당시에 사용된 토크나이저가 읽어짐

In [ ]:
# A라는 버트토크나이저에서 '사과'를 40번으로 인코딩
# B라는 버트토크나이저에서 '사과'를 50번으로 인코딩

In [31]:
inputs = tokenizer('Football is a really fun [MASK].', return_tensors='tf')
inputs

{'input_ids': <tf.Tensor: shape=(1, 15), dtype=int32, numpy=
array([[    2,    42, 18990,  2013,  2040,  8383, 11376,    68, 12569,
        24203,    73,  5830,     4,    18,     3]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 15), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 15), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [32]:
inputs['input_ids']

<tf.Tensor: shape=(1, 15), dtype=int32, numpy=
array([[    2,    42, 18990,  2013,  2040,  8383, 11376,    68, 12569,
        24203,    73,  5830,     4,    18,     3]], dtype=int32)>

In [33]:
inputs['attention_mask']

<tf.Tensor: shape=(1, 15), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>

In [34]:
inputs['token_type_ids'] # 문장 구분 가능 # 문장마다 값이 다름

<tf.Tensor: shape=(1, 15), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [35]:
from transformers import FillMaskPipeline

In [36]:
pip = FillMaskPipeline(model = model, tokenizer = tokenizer)

In [38]:
pip('Football is a really fun [MASK].')

[{'score': 0.20145516097545624,
  'token': 25808,
  'token_str': 'time',
  'sequence': 'Football is a really fun time.'},
 {'score': 0.11116120964288712,
  'token': 2013,
  'token_str': '##t',
  'sequence': 'Football is a really funt.'},
 {'score': 0.082809679210186,
  'token': 23312,
  'token_str': '##ction',
  'sequence': 'Football is a really function.'},
 {'score': 0.04717687517404556,
  'token': 2076,
  'token_str': '##y',
  'sequence': 'Football is a really funy.'},
 {'score': 0.03421862795948982,
  'token': 21744,
  'token_str': '##ning',
  'sequence': 'Football is a really funning.'}]

In [17]:
pip('I went to [MASK] this morning.')

[{'score': 0.3573073446750641,
  'token': 2147,
  'token_str': 'work',
  'sequence': 'i went to work this morning.'},
 {'score': 0.23304398357868195,
  'token': 2793,
  'token_str': 'bed',
  'sequence': 'i went to bed this morning.'},
 {'score': 0.1284506916999817,
  'token': 2082,
  'token_str': 'school',
  'sequence': 'i went to school this morning.'},
 {'score': 0.06230578571557999,
  'token': 3637,
  'token_str': 'sleep',
  'sequence': 'i went to sleep this morning.'},
 {'score': 0.046952586621046066,
  'token': 2465,
  'token_str': 'class',
  'sequence': 'i went to class this morning.'}]

In [22]:
# 한국어 bert

In [19]:
model = TFBertForMaskedLM.from_pretrained('klue/bert-base', from_pt=True)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertForMaskedLM: ['bert.embeddings.position_ids', 'cls.predictions.decoder.bias']
- This IS expected if you are initializing TFBertForMaskedLM from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForMaskedLM from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


In [20]:
# 한국어 버트 모델
tokenizer = AutoTokenizer.from_pretrained("klue/bert-base")

In [25]:
inputs = tokenizer('축구는 정말 재미있는 [MASK]다.', return_tensors='tf')

In [26]:
inputs

{'input_ids': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=
array([[   2, 4713, 2259, 3944, 6001, 2259,    4,  809,   18,    3]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [27]:
pip = FillMaskPipeline(model=model, tokenizer=tokenizer)

In [28]:
pip('축구는 정말 재미있는 [MASK]이다.')

[{'score': 0.7266969084739685,
  'token': 4559,
  'token_str': '스포츠',
  'sequence': '축구는 정말 재미있는 스포츠 이다.'},
 {'score': 0.08685805648565292,
  'token': 4171,
  'token_str': '게임',
  'sequence': '축구는 정말 재미있는 게임 이다.'},
 {'score': 0.05813439190387726,
  'token': 575,
  'token_str': '것',
  'sequence': '축구는 정말 재미있는 것 이다.'},
 {'score': 0.024134568870067596,
  'token': 5260,
  'token_str': '종목',
  'sequence': '축구는 정말 재미있는 종목 이다.'},
 {'score': 0.02265181951224804,
  'token': 3815,
  'token_str': '운동',
  'sequence': '축구는 정말 재미있는 운동 이다.'}]

In [29]:
pip('나는 방금 [MASK]를 먹었다.')

[{'score': 0.05272819101810455,
  'token': 10058,
  'token_str': '디저트',
  'sequence': '나는 방금 디저트 를 먹었다.'},
 {'score': 0.05258025601506233,
  'token': 14995,
  'token_str': '햄버거',
  'sequence': '나는 방금 햄버거 를 먹었다.'},
 {'score': 0.05081625655293465,
  'token': 13309,
  'token_str': '샌드위치',
  'sequence': '나는 방금 샌드위치 를 먹었다.'},
 {'score': 0.03278220072388649,
  'token': 11130,
  'token_str': '스테이크',
  'sequence': '나는 방금 스테이크 를 먹었다.'},
 {'score': 0.02911238744854927,
  'token': 8395,
  'token_str': '피자',
  'sequence': '나는 방금 피자 를 먹었다.'}]

In [30]:
from transformers import TFBertForNextSentencePrediction

In [40]:
model = TFBertForNextSentencePrediction.from_pretrained('bert-base-uncased')

All PyTorch model weights were used when initializing TFBertForNextSentencePrediction.

All the weights of TFBertForNextSentencePrediction were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForNextSentencePrediction for predictions without further training.


In [41]:
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

In [42]:
prompt = "In Italy, pizza served in formal settings, such as at a restaurant, is presented unsliced."
next_sentence = "pizza is eaten with the use of a knife and fork. In casual settings, however, it is cut into wedges to be eaten while held in the hand."

In [43]:
encoding = tokenizer(prompt,next_sentence,return_tensors='tf')

In [44]:
encoding

{'input_ids': <tf.Tensor: shape=(1, 58), dtype=int32, numpy=
array([[  101,  1999,  3304,  1010, 10733,  2366,  1999,  5337, 10906,
         1010,  2107,  2004,  2012,  1037,  4825,  1010,  2003,  3591,
         4895, 14540,  6610,  2094,  1012,   102, 10733,  2003,  8828,
         2007,  1996,  2224,  1997,  1037,  5442,  1998,  9292,  1012,
         1999, 10017, 10906,  1010,  2174,  1010,  2009,  2003,  3013,
         2046, 17632,  2015,  2000,  2022,  8828,  2096,  2218,  1999,
         1996,  2192,  1012,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 58), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 58), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [49]:
tokenizer.decode(encoding['input_ids'][0])

'[CLS] in italy, pizza served in formal settings, such as at a restaurant, is presented unsliced. [SEP] pizza is eaten with the use of a knife and fork. in casual settings, however, it is cut into wedges to be eaten while held in the hand. [SEP]'

In [52]:
logits = model(encoding['input_ids'],encoding['token_type_ids'])[0]
logits

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 2.6869488, -1.4650854]], dtype=float32)>

In [53]:
import tensorflow as tf

In [58]:
soft = tf.keras.layers.Softmax()
res = soft(logits)
res

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.98451126, 0.0154887 ]], dtype=float32)>

In [62]:
tf.math.argmax(res, axis = -1 ).numpy()[0]
# 0이면 이어지는 문장이라 볼 수 있다.

0

In [81]:
model = TFBertForNextSentencePrediction.from_pretrained('bert-base-uncased')

All PyTorch model weights were used when initializing TFBertForNextSentencePrediction.

All the weights of TFBertForNextSentencePrediction were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForNextSentencePrediction for predictions without further training.


In [82]:
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

In [88]:
prompt = "In Italy, pizza served in formal settings, such as at a restaurant, is presented unsliced."
nt_sentence = "Hi, Nice to meet you."

In [89]:
encoding = tokenizer(prompt,nt_sentence,return_tensors='tf')

In [90]:
logits = model(encoding['input_ids'],encoding['token_type_ids'])[0]

In [91]:
soft = tf.keras.layers.Softmax()
res = soft(logits)
res

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.9976714 , 0.00232857]], dtype=float32)>

In [92]:
tf.math.argmax(res, axis = -1 ).numpy()[0]

0