In [17]:
pip install transformers # GPT : pre_trained_model

In [53]:
import numpy as np
import random
import tensorflow as tf
from transformers import AutoTokenizer
from transformers import TFGPT2LMHeadModel
# gpt-2 -> finetuning(파인튜닝) -> 한국어 gpt2모델

In [20]:
model = TFGPT2LMHeadModel.from_pretrained("skt/kogpt2-base-v2",from_pt = True)

config.json:   0%|          | 0.00/1.00k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/513M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFGPT2LMHeadModel: ['transformer.h.2.attn.masked_bias', 'transformer.h.5.attn.masked_bias', 'transformer.h.1.attn.masked_bias', 'transformer.h.3.attn.masked_bias', 'lm_head.weight', 'transformer.h.8.attn.masked_bias', 'transformer.h.6.attn.masked_bias', 'transformer.h.0.attn.masked_bias', 'transformer.h.11.attn.masked_bias', 'transformer.h.9.attn.masked_bias', 'transformer.h.4.attn.masked_bias', 'transformer.h.10.attn.masked_bias', 'transformer.h.7.attn.masked_bias']
- This IS expected if you are initializing TFGPT2LMHeadModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFGPT2LMHeadModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassifica

In [21]:
tokenizer = AutoTokenizer.from_pretrained("skt/kogpt2-base-v2")

tokenizer.json:   0%|          | 0.00/2.83M [00:00<?, ?B/s]

In [37]:
sent = "프로젝트를 성공적하려면 팀원들은"

In [38]:
input_ids = tokenizer.encode(sent)

In [39]:
input_ids = tf.convert_to_tensor([input_ids])
input_ids # 2차원 구조로 변환

<tf.Tensor: shape=(1, 7), dtype=int32, numpy=array([[21835, 12498, 10363,  8186, 19352, 13717, 34686]], dtype=int32)>

In [40]:
output = model.generate(input_ids, max_length = 128, repetition_penalty = 2.0, use_cache = True) # repetition_penalty : 등장한 단어 최대한 안나오게

In [41]:
output_ids = output.numpy().tolist()[0] # 토크나이저의 decode함수로 전달하기 위해 단일 리스트 구조로 변경
output_ids

[21835,
 12498,
 10363,
 8186,
 19352,
 13717,
 34686,
 10769,
 18401,
 10852,
 9304,
 49686,
 9178,
 8146,
 7399,
 10943,
 22301,
 37921,
 9680,
 9094,
 19395,
 9224,
 33497,
 10416,
 8705,
 9025,
 9080,
 10586,
 25012,
 10341,
 9243,
 10094,
 26421,
 387,
 9456,
 8711,
 9052,
 9172,
 8612,
 8104,
 9226,
 13310,
 8137,
 11693,
 10387,
 11940,
 7799,
 30337,
 13439,
 17252,
 9277,
 9199,
 13366,
 9989,
 9207,
 9188,
 15424,
 11533,
 9882,
 15591,
 10001,
 9119,
 6825,
 9064,
 9449,
 40352,
 12042,
 8149,
 10134,
 11477,
 20757,
 9839,
 20759,
 9029,
 7335,
 8704,
 42136,
 14805,
 20279,
 9154,
 9422,
 46391,
 7844,
 7235,
 22603,
 10686,
 9156,
 12715,
 10735,
 12199,
 16846,
 9604,
 9174,
 33230,
 13363,
 9018,
 9673,
 11570,
 9180,
 9034,
 39696,
 9036,
 7487,
 8139,
 15266,
 16844,
 9430,
 9919,
 38424,
 9033,
 15148,
 16627,
 6963,
 8042,
 6958,
 32334,
 10201,
 9640,
 8056,
 26829,
 17336,
 8143,
 15263,
 11420,
 9947,
 27334,
 16493,
 21030]

In [42]:
tokenizer.decode(output_ids)

'프로젝트를 성공적하려면 팀원들은 물론 직원들도 함께 노력해야 한다.\n이런 점에서 이번 행사는 조직 내 구성원들의 역량을 강화할 수 있는 좋은 기회가 될 것으로 보인다.\n특히, 올해에는 ‘팀원 간 화합을 통한 업무 효율성 제고’를 목표로 하는 것이 특징이다.\n이를 위해 각 부서별로 다양한 프로그램을 운영한다.\n각 부서는 매주 수요일마다 모여 토론회를 열고 있다.\n또한 직원들의 의견을 수렴하기 위한 워크숍도 정기적으로 개최된다.\n이와 더불어 지난해에 이어 두 번째로 열린 이 날 행사에서는 전 직원이 한마음 체육대회를 통해 서로 소통하는 시간을 가졌다.\n김영기 본부장은 “올해는 그동안의 성과를 바탕으로 더욱 발전된 모습으로 업무에'

In [43]:
output = model(input_ids)

In [44]:
output.logits # (1, 7, 51200) 51200개 단어

<tf.Tensor: shape=(1, 7, 51200), dtype=float32, numpy=
array([[[-6.140402  , -5.859082  , -5.178856  , ..., -3.4393203 ,
         -2.6944485 , -3.563459  ],
        [-4.420429  , -3.9891706 , -4.9624968 , ..., -2.7080774 ,
         -2.3276203 ,  2.5232625 ],
        [-4.832242  , -4.7837524 , -5.5392814 , ..., -6.709307  ,
         -2.8316736 , -0.70310223],
        ...,
        [-6.256604  , -5.326578  , -6.3690896 , ..., -2.0338976 ,
         -4.352981  , -2.152663  ],
        [-6.849958  , -6.2379227 , -7.313833  , ..., -6.7263823 ,
         -5.3868265 , -4.29797   ],
        [-5.587227  , -4.803976  , -6.2501545 , ..., -0.5858772 ,
         -4.4394026 , -1.127749  ]]], dtype=float32)>

In [46]:
top10 = tf.math.top_k(output.logits[0,-1] , k = 10)

In [48]:
top10.indices.numpy()

array([10769, 31089, 13717,  9432, 12086,  9919, 21087,  9745, 25541,
        9036], dtype=int32)

In [49]:
tokenizer.convert_ids_to_tokens(top10.indices.numpy())

['▁물론', '▁물론이고', '▁팀', '▁모두', '▁항상', '▁서로', '▁각자', '▁자신의', '▁각자의', '▁한']

In [50]:
sent = "인공지능 전문가가 되기 위해서"

In [51]:
input_ids = tokenizer.encode(sent)

In [52]:
while (len(input_ids)<50):
    output = model(np.array([input_ids]))
    top5 = tf.math.top_k(output.logits[0, -1], k=5)
    token_id = random.choice(top5.indices.numpy())
    input_ids.append(token_id)
tokenizer.decode(input_ids)

'인공지능 전문가가 되기 위해서도 꼭 필요하다.\n또, 현재 국내 로봇시장은 인공관절수술이 주를 이루는 가운데 최근에는 다양한 수술로봇이 개발되는 등 인공관절에 대한 인식이 많이 변화되고 있는 추세여서 앞으로 더욱 많은 수의 로봇을 도입'

In [54]:
sent1 = "안녕하세요 gpt에 대해 소개해주세요."

In [55]:
input_ids = tokenizer.encode(sent1)

In [56]:
input_ids = tf.convert_to_tensor([input_ids])
input_ids # 2차원 구조로 변환

<tf.Tensor: shape=(1, 13), dtype=int32, numpy=
array([[25906,  8702,  7801,  8084, 15317,   454,   458,  8022,  9552,
        11725, 15084,  7801, 25856]], dtype=int32)>

In [58]:
output = model.generate(input_ids, max_length = 128, repetition_penalty = 1.0, use_cache = True) # repetition_penalty : 등장한 단어 최대한 안나오게